/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionRecord {
  'id' : bigint,
  'bed' : string,
  'status' : AdmissionStatus,
  'consultantEmail' : string,
  'admittedAt' : bigint,
  'admittedBy' : Principal,
  'patientId' : bigint,
  'ward' : string,
  'updatedAt' : bigint,
  'dischargedAt' : [] | [bigint],
  'admittedByRole' : StaffRole,
  'department' : string,
}
export type AdmissionStatus = { 'discharged' : null } |
  { 'admitted' : null } |
  { 'transferred' : null };
export type AlertSeverity = { 'Info' : null } |
  { 'Critical' : null } |
  { 'Warning' : null };
export type AlertType = { 'AKI' : null } |
  { 'Hypotension' : null } |
  { 'CriticalLab' : null } |
  { 'Sepsis' : null } |
  { 'DrugInteraction' : null } |
  { 'Hypoxia' : null } |
  { 'MissedDoseEscalation' : null } |
  { 'AllergyContraindication' : null };
export interface Appointment {
  'id' : string,
  'status' : AppointmentStatus,
  'patientId' : [] | [bigint],
  'date' : string,
  'createdAt' : bigint,
  'chamberName' : [] | [string],
  'registerNumber' : [] | [string],
  'appointmentType' : AppointmentType,
  'updatedAt' : bigint,
  'serialNumber' : [] | [bigint],
  'notes' : [] | [string],
  'patientName' : string,
  'hospitalName' : [] | [string],
  'phone' : [] | [string],
  'doctorEmail' : string,
  'timeSlot' : [] | [string],
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type AppointmentType = { 'hospital' : null } |
  { 'chamber' : null };
export interface AuditEntry {
  'id' : bigint,
  'changedByName' : string,
  'changedByRole' : StaffRole,
  'changedAt' : bigint,
  'changedBy' : Principal,
  'entityId' : bigint,
  'afterValue' : string,
  'beforeValue' : [] | [string],
  'entityType' : string,
  'fieldName' : string,
  'ipAddress' : [] | [string],
  'reason' : [] | [string],
}
export interface BedRecord {
  'id' : bigint,
  'status' : BedStatus,
  'patientId' : [] | [bigint],
  'admissionDate' : [] | [bigint],
  'transferHistory' : Array<BedTransferEntry>,
  'ward' : string,
  'bedNumber' : string,
  'updatedAt' : bigint,
  'patientName' : [] | [string],
  'dischargeDate' : [] | [bigint],
}
export type BedStatus = { 'Empty' : null } |
  { 'Maintenance' : null } |
  { 'Occupied' : null };
export interface BedTransferEntry {
  'toBed' : string,
  'date' : bigint,
  'fromBed' : string,
  'reason' : string,
}
export interface ClinicalAlert {
  'id' : bigint,
  'alertType' : AlertType,
  'acknowledgedAt' : [] | [bigint],
  'acknowledgedBy' : [] | [Principal],
  'patientId' : bigint,
  'isAcknowledged' : boolean,
  'isResolved' : boolean,
  'triggeredAt' : bigint,
  'triggeredBy' : string,
  'message' : string,
  'details' : [] | [string],
  'severity' : AlertSeverity,
  'resolvedAt' : [] | [bigint],
}
export interface ClinicalNote {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'patientId' : bigint,
  'authorId' : Principal,
  'createdAt' : bigint,
  'authorName' : string,
  'authorRole' : StaffRole,
  'noteType' : NoteType,
  'isDraft' : boolean,
  'previousVersionIds' : Array<bigint>,
  'versionInfo' : VersionedRecord,
  'encounterId' : [] | [bigint],
  'noteSubtype' : [] | [string],
}
export interface ClinicalOrder {
  'id' : bigint,
  'status' : OrderStatus,
  'completedAt' : [] | [bigint],
  'result' : [] | [string],
  'patientId' : bigint,
  'code' : string,
  'description' : string,
  'orderType' : OrderType,
  'orderedAt' : bigint,
  'orderedBy' : Principal,
  'notes' : [] | [string],
  'orderedByName' : string,
  'orderedByRole' : StaffRole,
  'versionInfo' : VersionedRecord,
  'encounterId' : [] | [bigint],
}
export interface CurrentUser { 'principal' : Principal, 'role' : UserRole }
export type DailyNoteState = { 'submittedToMO' : null } |
  { 'finalized' : null } |
  { 'rejected' : null } |
  { 'moReviewComplete' : null } |
  { 'draft' : null };
export interface DailyProgressNote {
  'id' : bigint,
  'moAssessment' : string,
  'isDeleted' : boolean,
  'drainMonitoring' : [] | [string],
  'internObjective' : string,
  'patientId' : bigint,
  'authorId' : Principal,
  'consultantComments' : string,
  'submittedByRole' : [] | [StaffRole],
  'consultantOverrides' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'reviewedByMO' : [] | [string],
  'authorRole' : StaffRole,
  'noteDate' : string,
  'rejectionReason' : [] | [string],
  'objectiveVitals' : [] | [string],
  'assessmentText' : string,
  'subjectiveComplaints' : Array<string>,
  'isDraft' : boolean,
  'updatedAt' : bigint,
  'activeDiagnoses' : Array<string>,
  'internSubjective' : string,
  'progressType' : DailyProgressType,
  'activeComplaints' : Array<string>,
  'moPlan' : string,
  'noteState' : DailyNoteState,
  'previousVersionIds' : Array<bigint>,
  'reviewedByConsultant' : [] | [string],
  'versionChain' : Array<string>,
  'versionInfo' : VersionedRecord,
  'submitTimestamp' : [] | [bigint],
  'encounterId' : [] | [bigint],
  'planText' : string,
  'systemReview' : [] | [string],
  'intakeOutput' : [] | [string],
  'investigations' : Array<string>,
}
export interface DailyProgressNoteUpdate {
  'moAssessment' : string,
  'drainMonitoring' : [] | [string],
  'internObjective' : string,
  'consultantComments' : string,
  'consultantOverrides' : string,
  'objectiveVitals' : [] | [string],
  'assessmentText' : string,
  'subjectiveComplaints' : Array<string>,
  'activeDiagnoses' : Array<string>,
  'internSubjective' : string,
  'activeComplaints' : Array<string>,
  'moPlan' : string,
  'planText' : string,
  'systemReview' : [] | [string],
  'intakeOutput' : [] | [string],
  'investigations' : Array<string>,
}
export type DailyProgressType = { 'morning' : null } |
  { 'evening' : null } |
  { 'emergency' : null };
export interface DiagnosisTemplate {
  'id' : bigint,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'icdCode' : [] | [string],
  'isActive' : boolean,
  'defaultDrugs' : Array<string>,
  'defaultAdvice' : Array<string>,
  'defaultInvestigations' : Array<string>,
  'diagnosisNameBn' : [] | [string],
  'diagnosisName' : string,
  'defaultAdviceBn' : Array<string>,
}
export interface Encounter {
  'id' : bigint,
  'status' : EncounterStatus,
  'encounterType' : EncounterType,
  'endDate' : [] | [bigint],
  'patientId' : bigint,
  'previousVersions' : Array<VersionedRecord>,
  'providerName' : string,
  'providerId' : Principal,
  'versionInfo' : VersionedRecord,
  'encounterId' : string,
  'locationNotes' : [] | [string],
  'startDate' : bigint,
}
export type EncounterStatus = { 'Planned' : null } |
  { 'Cancelled' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export type EncounterType = { 'IPD' : null } |
  { 'OPD' : null } |
  { 'FollowUp' : null } |
  { 'Emergency' : null };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface HandoverEntry {
  'id' : bigint,
  'status' : HandoverStatus,
  'takenByName' : [] | [string],
  'takenByRole' : [] | [StaffRole],
  'clinicalSummary' : string,
  'currentConsultant' : [] | [string],
  'consultantComment' : [] | [string],
  'patientId' : bigint,
  'dayOfStay' : [] | [bigint],
  'createdAt' : bigint,
  'ward' : [] | [string],
  'pendingInvestigations' : Array<string>,
  'vitalsSummary' : [] | [string],
  'bedNumber' : [] | [string],
  'registerNumber' : [] | [string],
  'diagnosis' : [] | [string],
  'missedMedications' : Array<string>,
  'shift' : HandoverShift,
  'updatedAt' : bigint,
  'givenByPrincipal' : Principal,
  'givenByName' : string,
  'consultantCommentAt' : [] | [bigint],
  'consultantCommentBy' : [] | [Principal],
  'givenByRole' : StaffRole,
  'takenByPrincipal' : [] | [Principal],
  'patientName' : string,
  'shiftEndTime' : bigint,
  'pendingProcedures' : Array<string>,
  'tasksPending' : Array<string>,
  'versionInfo' : VersionedRecord,
  'shiftStartTime' : bigint,
  'actionableItems' : Array<string>,
}
export type HandoverShift = { 'morning' : null } |
  { 'evening' : null } |
  { 'night' : null };
export type HandoverStatus = { 'submitted' : null } |
  { 'draft' : null };
export interface Medication {
  'duration' : string,
  'dose' : string,
  'name' : string,
  'instructions' : string,
  'frequency' : string,
}
export interface MedicationAdministration {
  'id' : bigint,
  'status' : MedicationAdministrationStatus,
  'medicationName' : string,
  'patientId' : bigint,
  'scheduledTime' : bigint,
  'dose' : string,
  'createdAt' : bigint,
  'recordedBy' : string,
  'updatedAt' : bigint,
  'recordedByRole' : string,
  'administeredAt' : [] | [bigint],
  'missedReason' : [] | [string],
}
export type MedicationAdministrationStatus = { 'Given' : null } |
  { 'Delayed' : null } |
  { 'NotGiven' : null };
export interface Medication__1 {
  'duration' : string,
  'dose' : string,
  'name' : string,
  'prnCondition' : [] | [string],
  'instructions' : [] | [string],
  'frequency' : string,
  'isPRN' : boolean,
  'route' : string,
}
export type NoteType = { 'SOAP' : null } |
  { 'Nursing' : null } |
  { 'DailyProgress' : null } |
  { 'General' : null } |
  { 'Handover' : null } |
  { 'Discharge' : null };
export interface Observation {
  'id' : bigint,
  'status' : ObservationStatus,
  'enteredByRole' : [] | [StaffRole],
  'isDeleted' : boolean,
  'numericValue' : [] | [number],
  'vitalVerificationStatus' : [] | [VitalVerificationStatus],
  'value' : string,
  'observationDate' : bigint,
  'patientId' : bigint,
  'observationType' : ObservationType,
  'code' : string,
  'unit' : string,
  'rejectionReason' : [] | [string],
  'recordedBy' : Principal,
  'normalRange' : [] | [string],
  'recordedByName' : string,
  'recordedByRole' : StaffRole,
  'interpretation' : [] | [string],
  'versionInfo' : VersionedRecord,
  'encounterId' : [] | [bigint],
  'verifiedAt' : [] | [bigint],
  'verifiedBy' : [] | [Principal],
  'enteredBy' : [] | [Principal],
}
export type ObservationStatus = { 'Corrected' : null } |
  { 'Final' : null } |
  { 'Preliminary' : null };
export type ObservationType = { 'Lab' : null } |
  { 'ExamFinding' : null } |
  { 'DrainMonitoring' : null } |
  { 'IntakeOutput' : null } |
  { 'Vital' : null };
export type OrderStatus = { 'Requested' : null } |
  { 'Cancelled' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type OrderType = { 'Medication' : null } |
  { 'Procedure' : null } |
  { 'Investigation' : null } |
  { 'LabTest' : null };
export interface Patient {
  'id' : bigint,
  'weight' : [] | [number],
  'height' : [] | [number],
  'consultantEmail' : [] | [string],
  'nameBn' : [] | [string],
  'consultantName' : [] | [string],
  'dateOfBirth' : [] | [Time],
  'createdAt' : Time,
  'fullName' : string,
  'email' : [] | [string],
  'updatedAt' : Time,
  'pastSurgicalHistory' : [] | [string],
  'bloodGroup' : [] | [string],
  'address' : [] | [string],
  'gender' : Gender,
  'patientType' : PatientType,
  'chronicConditions' : Array<string>,
  'phone' : [] | [string],
  'allergies' : Array<string>,
}
export type PatientType = { 'admitted' : null } |
  { 'outdoor' : null };
export interface Prescription {
  'id' : bigint,
  'patientId' : bigint,
  'createdAt' : Time,
  'diagnosis' : [] | [string],
  'prescriptionDate' : Time,
  'updatedAt' : Time,
  'medications' : Array<Medication>,
  'notes' : [] | [string],
  'visitId' : [] | [bigint],
}
export interface Prescription__1 {
  'id' : bigint,
  'isDeleted' : boolean,
  'patientId' : bigint,
  'followUpCreatesAppointment' : boolean,
  'authorId' : Principal,
  'createdAt' : bigint,
  'authorName' : string,
  'authorRole' : StaffRole,
  'diagnoses' : Array<string>,
  'isDraft' : boolean,
  'isFinalized' : boolean,
  'updatedAt' : bigint,
  'medications' : Array<Medication__1>,
  'advice' : Array<string>,
  'versionInfo' : VersionedRecord,
  'encounterId' : [] | [bigint],
  'followUpDate' : [] | [bigint],
}
export type QueueStatus = { 'serving' : null } |
  { 'skipped' : null } |
  { 'done' : null } |
  { 'waiting' : null };
export interface RoleChangeEntry {
  'id' : bigint,
  'principal' : Principal,
  'changedBy' : Principal,
  'timestamp' : bigint,
  'previousRole' : [] | [StaffRole],
  'newRole' : StaffRole,
}
export interface SerialQueueEntry {
  'id' : string,
  'status' : QueueStatus,
  'date' : string,
  'createdAt' : bigint,
  'registerNumber' : [] | [string],
  'calledAt' : [] | [bigint],
  'updatedAt' : bigint,
  'serialNumber' : bigint,
  'patientName' : string,
  'phone' : [] | [string],
  'doctorEmail' : string,
}
export type StaffRole = { 'assistant_registrar' : null } |
  { 'professor' : null } |
  { 'patient' : null } |
  { 'admin' : null } |
  { 'doctor' : null } |
  { 'medical_officer' : null } |
  { 'intern_doctor' : null } |
  { 'associate_professor' : null } |
  { 'assistant_professor' : null } |
  { 'consultant_doctor' : null } |
  { 'staff' : null } |
  { 'nurse' : null } |
  { 'registrar' : null };
export interface SyncData {
  'queueEntries' : Array<SerialQueueEntry>,
  'appointments' : Array<Appointment>,
  'timestamp' : bigint,
}
export interface SyncRecord {
  'id' : bigint,
  'lastEntityType' : [] | [string],
  'userId' : Principal,
  'pendingChanges' : bigint,
  'deviceId' : string,
  'lastSyncAt' : bigint,
  'lastEntityId' : [] | [bigint],
}
export type Time = bigint;
export interface UpdatedData {
  'queueEntries' : Array<SerialQueueEntry>,
  'appointments' : Array<Appointment>,
  'timestamp' : bigint,
  'patients' : Array<bigint>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VersionedRecord {
  'createdAt' : bigint,
  'createdBy' : Principal,
  'version' : bigint,
  'createdByName' : string,
  'createdByRole' : StaffRole,
  'changeReason' : [] | [string],
}
export interface Visit {
  'id' : bigint,
  'vitalSigns' : VitalSigns,
  'patientId' : bigint,
  'createdAt' : Time,
  'visitDate' : Time,
  'visitType' : VisitType,
  'diagnosis' : [] | [string],
  'updatedAt' : Time,
  'historyOfPresentIllness' : [] | [string],
  'notes' : [] | [string],
  'physicalExamination' : [] | [string],
  'chiefComplaint' : string,
}
export type VisitType = { 'admitted' : null } |
  { 'outdoor' : null };
export interface VitalSigns {
  'respiratoryRate' : [] | [string],
  'temperature' : [] | [string],
  'bloodPressure' : [] | [string],
  'oxygenSaturation' : [] | [string],
  'pulse' : [] | [string],
}
export type VitalVerificationStatus = { 'pendingMOReview' : null } |
  { 'verifiedByMO' : null } |
  { 'finalized' : null } |
  { 'rejected' : null } |
  { 'drafted' : null };
export interface VitalsSummary {
  'bp' : [] | [string],
  'rr' : [] | [string],
  'rbs' : [] | [string],
  'spo2' : [] | [string],
  'temp' : [] | [string],
  'recordedAt' : bigint,
  'pulse' : [] | [string],
}
export interface WardRoundPatientStatus {
  'admissionDay' : bigint,
  'patientId' : string,
  'todayNoteState' : [] | [string],
  'assignedConsultant' : [] | [string],
  'ward' : string,
  'bedNumber' : string,
  'activeAlerts' : Array<string>,
  'patientName' : string,
  'lastVitals' : [] | [VitalsSummary],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeAlert' : ActorMethod<
    [bigint],
    { 'ok' : ClinicalAlert } |
      { 'err' : string }
  >,
  'acknowledgeHandover' : ActorMethod<
    [bigint],
    { 'ok' : HandoverEntry } |
      { 'err' : string }
  >,
  'acknowledgeObservationCorrection' : ActorMethod<
    [bigint, string, string],
    { 'ok' : Observation } |
      { 'err' : string }
  >,
  'addAuditEntry' : ActorMethod<
    [string, bigint, string, [] | [string], string, [] | [string]],
    undefined
  >,
  'addNoteAddendum' : ActorMethod<
    [bigint, bigint, string],
    { 'ok' : DailyProgressNote } |
      { 'err' : string }
  >,
  'approveDischarge' : ActorMethod<
    [bigint],
    { 'ok' : AdmissionRecord } |
      { 'err' : string }
  >,
  'assignBed' : ActorMethod<
    [bigint, bigint, string],
    { 'ok' : BedRecord } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignConsultant' : ActorMethod<[bigint, string, string], Patient>,
  'bulkUpsertAppointments' : ActorMethod<
    [Array<Appointment>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'bulkUpsertBeds' : ActorMethod<[Array<BedRecord>], Array<BedRecord>>,
  'bulkUpsertDailyProgressNotes' : ActorMethod<
    [Array<DailyProgressNote>],
    Array<DailyProgressNote>
  >,
  'bulkUpsertHandovers' : ActorMethod<
    [Array<HandoverEntry>],
    Array<HandoverEntry>
  >,
  'bulkUpsertMedicationAdministrations' : ActorMethod<
    [Array<MedicationAdministration>],
    Array<MedicationAdministration>
  >,
  'bulkUpsertObservations' : ActorMethod<
    [Array<Observation>],
    Array<Observation>
  >,
  'bulkUpsertPatients' : ActorMethod<[Array<Patient>], Array<Patient>>,
  'bulkUpsertPrescriptions' : ActorMethod<
    [Array<Prescription>],
    Array<Prescription>
  >,
  'bulkUpsertQueueEntries' : ActorMethod<
    [Array<SerialQueueEntry>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'bulkUpsertVisits' : ActorMethod<[Array<Visit>], Array<Visit>>,
  'clearQueueByDate' : ActorMethod<
    [string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'createAdmission' : ActorMethod<
    [bigint, string, string, string, string],
    { 'ok' : AdmissionRecord } |
      { 'err' : string }
  >,
  'createAppointment' : ActorMethod<
    [
      string,
      [] | [bigint],
      string,
      [] | [string],
      [] | [string],
      AppointmentType,
      [] | [string],
      [] | [string],
      string,
      [] | [string],
      AppointmentStatus,
      string,
      [] | [bigint],
      [] | [string],
    ],
    { 'ok' : Appointment } |
      { 'err' : string }
  >,
  'createBedRecord' : ActorMethod<
    [string, string],
    { 'ok' : BedRecord } |
      { 'err' : string }
  >,
  'createClinicalAlert' : ActorMethod<
    [bigint, AlertType, AlertSeverity, string, [] | [string]],
    { 'ok' : ClinicalAlert } |
      { 'err' : string }
  >,
  'createClinicalNote' : ActorMethod<
    [bigint, [] | [bigint], NoteType, [] | [string], string, boolean],
    { 'ok' : ClinicalNote } |
      { 'err' : string }
  >,
  'createClinicalPrescription' : ActorMethod<
    [
      bigint,
      [] | [bigint],
      Array<Medication__1>,
      Array<string>,
      Array<string>,
      [] | [bigint],
      boolean,
      boolean,
    ],
    { 'ok' : Prescription__1 } |
      { 'err' : string }
  >,
  'createDailyProgressNote' : ActorMethod<
    [
      bigint,
      [] | [bigint],
      DailyProgressType,
      string,
      Array<string>,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      Array<string>,
      string,
      string,
      Array<string>,
      Array<string>,
      boolean,
    ],
    { 'ok' : DailyProgressNote } |
      { 'err' : string }
  >,
  'createDiagnosisTemplate' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    { 'ok' : DiagnosisTemplate } |
      { 'err' : string }
  >,
  'createEncounter' : ActorMethod<
    [bigint, EncounterType, [] | [string]],
    { 'ok' : Encounter } |
      { 'err' : string }
  >,
  'createFollowUpAppointment' : ActorMethod<
    [bigint, bigint, bigint, string, string],
    { 'ok' : Appointment } |
      { 'err' : string }
  >,
  'createHandover' : ActorMethod<
    [
      bigint,
      HandoverShift,
      bigint,
      bigint,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
      string,
      [] | [string],
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    { 'ok' : HandoverEntry } |
      { 'err' : string }
  >,
  'createObservation' : ActorMethod<
    [
      bigint,
      [] | [bigint],
      ObservationType,
      string,
      string,
      [] | [number],
      string,
      [] | [string],
      [] | [string],
      bigint,
    ],
    { 'ok' : Observation } |
      { 'err' : string }
  >,
  'createOrder' : ActorMethod<
    [bigint, [] | [bigint], OrderType, string, string, [] | [string]],
    { 'ok' : ClinicalOrder } |
      { 'err' : string }
  >,
  'createPatient' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [Time],
      Gender,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [number],
      [] | [number],
      Array<string>,
      Array<string>,
      [] | [string],
      PatientType,
      [] | [string],
      [] | [string],
    ],
    Patient
  >,
  'createPrescription' : ActorMethod<
    [
      bigint,
      [] | [bigint],
      Time,
      [] | [string],
      Array<Medication>,
      [] | [string],
    ],
    Prescription
  >,
  'createQueueEntry' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      [] | [string],
      [] | [string],
      QueueStatus,
      [] | [bigint],
      string,
    ],
    { 'ok' : SerialQueueEntry } |
      { 'err' : string }
  >,
  'createVisit' : ActorMethod<
    [
      bigint,
      Time,
      string,
      [] | [string],
      VitalSigns,
      [] | [string],
      [] | [string],
      [] | [string],
      VisitType,
    ],
    Visit
  >,
  'deleteAppointment' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deletePatient' : ActorMethod<[bigint], undefined>,
  'deletePrescription' : ActorMethod<[bigint], undefined>,
  'deleteQueueEntry' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteVisit' : ActorMethod<[bigint], undefined>,
  'dischargeBed' : ActorMethod<
    [bigint],
    { 'ok' : BedRecord } |
      { 'err' : string }
  >,
  'dismissAlert' : ActorMethod<
    [bigint],
    { 'ok' : ClinicalAlert } |
      { 'err' : string }
  >,
  'finalizeClinicalPrescription' : ActorMethod<
    [bigint],
    { 'ok' : Prescription__1 } |
      { 'err' : string }
  >,
  'finalizeDailyNote' : ActorMethod<
    [bigint, bigint, string, string, DailyProgressNoteUpdate],
    { 'ok' : DailyProgressNote } |
      { 'err' : string }
  >,
  'finalizeNote' : ActorMethod<
    [bigint],
    { 'ok' : ClinicalNote } |
      { 'err' : string }
  >,
  'getActiveAlerts' : ActorMethod<[bigint], Array<ClinicalAlert>>,
  'getActiveOrdersByPatient' : ActorMethod<[bigint], Array<ClinicalOrder>>,
  'getAlertsByPatient' : ActorMethod<[bigint], Array<ClinicalAlert>>,
  'getAllAdmittedPatients' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [string], [] | [string]],
    { 'ok' : Array<AdmissionRecord> } |
      { 'err' : string }
  >,
  'getAllAppointmentsByDoctor' : ActorMethod<
    [string],
    { 'ok' : Array<Appointment> } |
      { 'err' : string }
  >,
  'getAllAuditEntries' : ActorMethod<[bigint, bigint], Array<AuditEntry>>,
  'getAllBeds' : ActorMethod<[], Array<BedRecord>>,
  'getAllBedsSince' : ActorMethod<[bigint], Array<BedRecord>>,
  'getAllDiagnosisTemplates' : ActorMethod<[], Array<DiagnosisTemplate>>,
  'getAllEncounters' : ActorMethod<[], Array<Encounter>>,
  'getAllHandoversSince' : ActorMethod<[bigint], Array<HandoverEntry>>,
  'getAllMedicationAdministrationsSince' : ActorMethod<
    [bigint],
    Array<MedicationAdministration>
  >,
  'getAllObservationsSince' : ActorMethod<[bigint], Array<Observation>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllPatientsSince' : ActorMethod<[bigint], Array<Patient>>,
  'getAllPrescriptions' : ActorMethod<[], Array<Prescription>>,
  'getAllPrescriptionsSince' : ActorMethod<[bigint], Array<Prescription>>,
  'getAllRoleChanges' : ActorMethod<
    [],
    { 'ok' : Array<RoleChangeEntry> } |
      { 'err' : string }
  >,
  'getAllVisits' : ActorMethod<[], Array<Visit>>,
  'getAllVisitsSince' : ActorMethod<[bigint], Array<Visit>>,
  'getAppointmentById' : ActorMethod<
    [string],
    { 'ok' : [] | [Appointment] } |
      { 'err' : string }
  >,
  'getAppointmentsByDoctor' : ActorMethod<
    [string, string],
    { 'ok' : Array<Appointment> } |
      { 'err' : string }
  >,
  'getAppointmentsSince' : ActorMethod<
    [string, bigint],
    { 'ok' : Array<Appointment> } |
      { 'err' : string }
  >,
  'getAuditLog' : ActorMethod<[bigint, bigint, bigint], Array<AuditEntry>>,
  'getAuditTrail' : ActorMethod<[bigint, bigint, bigint], Array<AuditEntry>>,
  'getAvailableBeds' : ActorMethod<[], Array<BedRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClinicalNotesByPatient' : ActorMethod<[bigint], Array<ClinicalNote>>,
  'getClinicalNotesByType' : ActorMethod<
    [bigint, NoteType],
    Array<ClinicalNote>
  >,
  'getClinicalPrescriptionsAwaitingApproval' : ActorMethod<
    [],
    Array<Prescription__1>
  >,
  'getClinicalPrescriptionsByPatient' : ActorMethod<
    [bigint],
    Array<Prescription__1>
  >,
  'getCurrentUser' : ActorMethod<[], CurrentUser>,
  'getDailyNotesByPatient' : ActorMethod<
    [bigint, [] | [string]],
    Array<DailyProgressNote>
  >,
  'getDailyProgressNotesByPatientId' : ActorMethod<
    [bigint],
    Array<DailyProgressNote>
  >,
  'getDailyProgressNotesSince' : ActorMethod<
    [bigint],
    Array<DailyProgressNote>
  >,
  'getDiagnosisTemplate' : ActorMethod<[bigint], [] | [DiagnosisTemplate]>,
  'getEmailIndex' : ActorMethod<
    [],
    { 'ok' : Array<[string, Principal]> } |
      { 'err' : string }
  >,
  'getEncountersByPatient' : ActorMethod<[bigint], Array<Encounter>>,
  'getFrontPageContent' : ActorMethod<[], [] | [string]>,
  'getFullSyncData' : ActorMethod<
    [string],
    { 'ok' : SyncData } |
      { 'err' : string }
  >,
  'getHandover' : ActorMethod<[bigint], [] | [HandoverEntry]>,
  'getHandoversByPatientId' : ActorMethod<[bigint], Array<HandoverEntry>>,
  'getLastSyncTime' : ActorMethod<[string], [] | [bigint]>,
  'getLastSyncTimestamp' : ActorMethod<[], bigint>,
  'getMedicationAdministrationsByPatient' : ActorMethod<
    [bigint],
    Array<MedicationAdministration>
  >,
  'getNotesAwaitingApproval' : ActorMethod<[], Array<ClinicalNote>>,
  'getObservationsByPatient' : ActorMethod<[bigint], Array<Observation>>,
  'getObservationsByType' : ActorMethod<
    [bigint, ObservationType],
    Array<Observation>
  >,
  'getOccupiedBeds' : ActorMethod<[], Array<BedRecord>>,
  'getOrdersByPatient' : ActorMethod<[bigint], Array<ClinicalOrder>>,
  'getPatient' : ActorMethod<[bigint], [] | [Patient]>,
  'getPrescription' : ActorMethod<[bigint], [] | [Prescription]>,
  'getPrescriptionsByPatientId' : ActorMethod<[bigint], Array<Prescription>>,
  'getPrescriptionsByVisitId' : ActorMethod<[bigint], Array<Prescription>>,
  'getQueueByDateAndDoctor' : ActorMethod<
    [string, string],
    { 'ok' : Array<SerialQueueEntry> } |
      { 'err' : string }
  >,
  'getQueueEntriesSince' : ActorMethod<
    [string, bigint],
    { 'ok' : Array<SerialQueueEntry> } |
      { 'err' : string }
  >,
  'getRoleChangeHistory' : ActorMethod<[Principal], Array<RoleChangeEntry>>,
  'getServerTimestamp' : ActorMethod<[], bigint>,
  'getUnacknowledgedAlerts' : ActorMethod<[], Array<ClinicalAlert>>,
  'getUpdatedData' : ActorMethod<
    [string, bigint],
    { 'ok' : UpdatedData } |
      { 'err' : string }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisit' : ActorMethod<[bigint], [] | [Visit]>,
  'getVisitsByPatientId' : ActorMethod<[bigint], Array<Visit>>,
  'getVitalsForVerification' : ActorMethod<[], Array<Observation>>,
  'getWardRoundStatus' : ActorMethod<[string], Array<WardRoundPatientStatus>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmailRegistered' : ActorMethod<[string], boolean>,
  'migrateFromLocalStorage' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'recordAISuggestionAccepted' : ActorMethod<
    [bigint, string, string, number],
    undefined
  >,
  'recordDeviceSync' : ActorMethod<
    [string, bigint],
    { 'ok' : SyncRecord } |
      { 'err' : string }
  >,
  'recordMedicationAdministration' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      [] | [bigint],
      MedicationAdministrationStatus,
      [] | [string],
    ],
    { 'ok' : MedicationAdministration } |
      { 'err' : string }
  >,
  'registerEmail' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'rejectDraftNote' : ActorMethod<
    [bigint, bigint, string, string],
    { 'ok' : DailyProgressNote } |
      { 'err' : string }
  >,
  'rejectVital' : ActorMethod<
    [bigint, string],
    { 'ok' : Observation } |
      { 'err' : string }
  >,
  'resolveAlert' : ActorMethod<
    [bigint],
    { 'ok' : ClinicalAlert } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFrontPageContent' : ActorMethod<[string], undefined>,
  'submitDailyNoteForReview' : ActorMethod<
    [bigint, bigint, DailyProgressNoteUpdate],
    { 'ok' : DailyProgressNote } |
      { 'err' : string }
  >,
  'syncData' : ActorMethod<[string], { 'ok' : SyncData } | { 'err' : string }>,
  'transferBed' : ActorMethod<
    [bigint, bigint, string],
    { 'ok' : BedRecord } |
      { 'err' : string }
  >,
  'updateAdmissionStatus' : ActorMethod<
    [bigint, AdmissionStatus],
    { 'ok' : AdmissionRecord } |
      { 'err' : string }
  >,
  'updateAppointment' : ActorMethod<
    [
      string,
      [] | [bigint],
      string,
      [] | [string],
      [] | [string],
      AppointmentType,
      [] | [string],
      [] | [string],
      string,
      [] | [string],
      AppointmentStatus,
      [] | [bigint],
      [] | [string],
    ],
    { 'ok' : Appointment } |
      { 'err' : string }
  >,
  'updateClinicalNote' : ActorMethod<
    [bigint, string, boolean, [] | [string]],
    { 'ok' : ClinicalNote } |
      { 'err' : string }
  >,
  'updateDailyProgressNote' : ActorMethod<
    [
      bigint,
      Array<string>,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      Array<string>,
      string,
      string,
      Array<string>,
      Array<string>,
      boolean,
      [] | [string],
    ],
    { 'ok' : DailyProgressNote } |
      { 'err' : string }
  >,
  'updateDiagnosisTemplate' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      [] | [string],
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    { 'ok' : DiagnosisTemplate } |
      { 'err' : string }
  >,
  'updateEncounter' : ActorMethod<
    [bigint, bigint, EncounterStatus, [] | [bigint], [] | [string]],
    { 'ok' : Encounter } |
      { 'err' : string }
  >,
  'updateHandover' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
      [] | [string],
      [] | [StaffRole],
      [] | [Principal],
      [] | [string],
      HandoverStatus,
    ],
    { 'ok' : HandoverEntry } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [bigint, OrderStatus, [] | [string], [] | [bigint]],
    { 'ok' : ClinicalOrder } |
      { 'err' : string }
  >,
  'updatePatient' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      [] | [Time],
      Gender,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [number],
      [] | [number],
      Array<string>,
      Array<string>,
      [] | [string],
      PatientType,
      [] | [string],
      [] | [string],
    ],
    Patient
  >,
  'updatePatientBedAssignment' : ActorMethod<
    [bigint, string],
    { 'ok' : AdmissionRecord } |
      { 'err' : string }
  >,
  'updatePrescription' : ActorMethod<
    [
      bigint,
      bigint,
      [] | [bigint],
      Time,
      [] | [string],
      Array<Medication>,
      [] | [string],
    ],
    Prescription
  >,
  'updateQueueEntry' : ActorMethod<
    [string, QueueStatus, [] | [bigint]],
    { 'ok' : SerialQueueEntry } |
      { 'err' : string }
  >,
  'updateVisit' : ActorMethod<
    [
      bigint,
      bigint,
      Time,
      string,
      [] | [string],
      VitalSigns,
      [] | [string],
      [] | [string],
      [] | [string],
      VisitType,
    ],
    Visit
  >,
  'upsertPatient' : ActorMethod<[Patient], Patient>,
  'upsertPrescription' : ActorMethod<[Prescription], Prescription>,
  'upsertVisit' : ActorMethod<[Visit], Visit>,
  'verifyVital' : ActorMethod<
    [bigint],
    { 'ok' : Observation } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];